services:
  backend:
    build:
      context: ./backend
    container_name: clinica-backend
    env_file:
      - ./backend/.env
    ports:
      - "5000:5000"

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_URL: http://localhost:5000
    container_name: clinica-frontend
    depends_on:
      - backend
    ports:
      - "3000:80"
